name: Hello World

on:
 push:
  branches:
   - main

jobs:
 hello_world_jobs:
  runs-on: ubuntu-latest

  steps:
   - name: Say Hello
     run: |
      echo "Hello World!"

  steps:
   - name: Now it is
     run: |
      date

  steps:
   - name: Directory content
     run: |
      ls -l
